### ISSUE TITLE
SwingLAF should use Swing colors rather than AWT colors

### ISSUE THREAD

**Issue by stacktracer** [metsci/glimpse#25]
SwingLookAndFeel should use Swing default colors (which are determined by Swing's current look-and-feel, and can be accessed through UIManager), rather than the AWT ones (static fields in SystemColor). E.g.:

```java
map.put( FRAME_BACKGROUND_COLOR, fromColorAwt( UIManager.getColor( "Panel.background" ) ) );
```

instead of

```java
map.put( FRAME_BACKGROUND_COLOR, fromColorAwt( SystemColor.window ) );
```

(Helpful for finding valid UIManager keys: http://nadeausoftware.com/node/85)

**Comment by ulmangt** [comment]
Looks like this has been fixed at some point since it was opened.
