### ISSUE TITLE
GLSL isnan() function not supported on OSX

### ISSUE THREAD

**Issue by orenbum** [metsci/glimpse#3]
OSX only supports up to GLSL v1.20 (see: https://developer.apple.com/graphicsimaging/opengl/capabilities/) which doesn't include the isnan() function. Trying to run the TaggedHeatMapExample results in the following error:

> INFO: Compiling 'PIPELINE colormap'...
> Mar 15, 2012 7:12:24 PM com.metsci.glimpse.gl.shader.GLShaderUtils logGLShaderInfoLog
> WARNING: COMPILATION FAILED: 'FRAGMENT SHADER tagged_colorscale_shader' did not compile.
> Mar 15, 2012 7:12:24 PM com.metsci.glimpse.gl.shader.GLShaderUtils logGLShaderInfoLog
> WARNING: ERROR: 0:33: Call to undeclared function 'isnan' 

I think the only shader this affects is the tagged_colorscale_shader.fs, which uses isnan() to discard values.

**Comment by ulmangt** [comment]
The call to isnan has been replaced with "x != x" which appears to have the same affect.
