### ISSUE TITLE
Why is EventPlotInfo.EventListener.hoveredEvents modifiable?

### ISSUE THREAD

**Issue by stacktracer** [metsci/glimpse#44]
At [EventPlotInfo line 321](https://github.com/metsci/glimpse/blob/master/core/src/main/java/com/metsci/glimpse/plot/timeline/event/EventPlotInfo.java#L321
), we make a modifiable copy of newHoveredEvents, and store it to this.hoveredEvents -- which, in mouseExited, gets passed to listeners. So the listeners get a modifiable copy of a set that seems to be for internal bookkeeping. Is this deliberate?

A listener could modify the set, which would cause confusing behavior. Also, we're doing an extra set clone to end up with the modifiable copy -- newHoveredEvents is unmodifiable.

**Comment by ulmangt** [comment]
I agree. It looks like the change is simply to not create the extra modifiable copy of newHoveredEvents.
